// flow-typed signature: 31a62e91e08216fe5e7bb401a97d6d12
// flow-typed version: <<STUB>>/babel-plugin-add-module-exports_v1.0.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-add-module-exports'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-add-module-exports' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-add-module-exports/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-add-module-exports/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-add-module-exports/lib/index'>;
}
