// flow-typed signature: d6d7d62705f04abe7a571d058b482288
// flow-typed version: <<STUB>>/concurrently_v^4.1.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'concurrently'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'concurrently' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'concurrently/bin/concurrently' {
  declare module.exports: any;
}

declare module 'concurrently/bin/concurrently.spec' {
  declare module.exports: any;
}

declare module 'concurrently/bin/fixtures/read-echo' {
  declare module.exports: any;
}

declare module 'concurrently/src/command-parser/expand-npm-shortcut' {
  declare module.exports: any;
}

declare module 'concurrently/src/command-parser/expand-npm-shortcut.spec' {
  declare module.exports: any;
}

declare module 'concurrently/src/command-parser/expand-npm-wildcard' {
  declare module.exports: any;
}

declare module 'concurrently/src/command-parser/expand-npm-wildcard.spec' {
  declare module.exports: any;
}

declare module 'concurrently/src/command-parser/strip-quotes' {
  declare module.exports: any;
}

declare module 'concurrently/src/command-parser/strip-quotes.spec' {
  declare module.exports: any;
}

declare module 'concurrently/src/command' {
  declare module.exports: any;
}

declare module 'concurrently/src/command.spec' {
  declare module.exports: any;
}

declare module 'concurrently/src/completion-listener' {
  declare module.exports: any;
}

declare module 'concurrently/src/completion-listener.spec' {
  declare module.exports: any;
}

declare module 'concurrently/src/concurrently' {
  declare module.exports: any;
}

declare module 'concurrently/src/concurrently.spec' {
  declare module.exports: any;
}

declare module 'concurrently/src/defaults' {
  declare module.exports: any;
}

declare module 'concurrently/src/flow-control/fixtures/fake-command' {
  declare module.exports: any;
}

declare module 'concurrently/src/flow-control/input-handler' {
  declare module.exports: any;
}

declare module 'concurrently/src/flow-control/input-handler.spec' {
  declare module.exports: any;
}

declare module 'concurrently/src/flow-control/kill-on-signal' {
  declare module.exports: any;
}

declare module 'concurrently/src/flow-control/kill-on-signal.spec' {
  declare module.exports: any;
}

declare module 'concurrently/src/flow-control/kill-others' {
  declare module.exports: any;
}

declare module 'concurrently/src/flow-control/kill-others.spec' {
  declare module.exports: any;
}

declare module 'concurrently/src/flow-control/log-error' {
  declare module.exports: any;
}

declare module 'concurrently/src/flow-control/log-error.spec' {
  declare module.exports: any;
}

declare module 'concurrently/src/flow-control/log-exit' {
  declare module.exports: any;
}

declare module 'concurrently/src/flow-control/log-exit.spec' {
  declare module.exports: any;
}

declare module 'concurrently/src/flow-control/log-output' {
  declare module.exports: any;
}

declare module 'concurrently/src/flow-control/log-output.spec' {
  declare module.exports: any;
}

declare module 'concurrently/src/flow-control/restart-process' {
  declare module.exports: any;
}

declare module 'concurrently/src/flow-control/restart-process.spec' {
  declare module.exports: any;
}

declare module 'concurrently/src/get-spawn-opts' {
  declare module.exports: any;
}

declare module 'concurrently/src/get-spawn-opts.spec' {
  declare module.exports: any;
}

declare module 'concurrently/src/logger' {
  declare module.exports: any;
}

declare module 'concurrently/src/logger.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'concurrently/bin/concurrently.js' {
  declare module.exports: $Exports<'concurrently/bin/concurrently'>;
}
declare module 'concurrently/bin/concurrently.spec.js' {
  declare module.exports: $Exports<'concurrently/bin/concurrently.spec'>;
}
declare module 'concurrently/bin/fixtures/read-echo.js' {
  declare module.exports: $Exports<'concurrently/bin/fixtures/read-echo'>;
}
declare module 'concurrently/index' {
  declare module.exports: $Exports<'concurrently'>;
}
declare module 'concurrently/index.js' {
  declare module.exports: $Exports<'concurrently'>;
}
declare module 'concurrently/src/command-parser/expand-npm-shortcut.js' {
  declare module.exports: $Exports<'concurrently/src/command-parser/expand-npm-shortcut'>;
}
declare module 'concurrently/src/command-parser/expand-npm-shortcut.spec.js' {
  declare module.exports: $Exports<'concurrently/src/command-parser/expand-npm-shortcut.spec'>;
}
declare module 'concurrently/src/command-parser/expand-npm-wildcard.js' {
  declare module.exports: $Exports<'concurrently/src/command-parser/expand-npm-wildcard'>;
}
declare module 'concurrently/src/command-parser/expand-npm-wildcard.spec.js' {
  declare module.exports: $Exports<'concurrently/src/command-parser/expand-npm-wildcard.spec'>;
}
declare module 'concurrently/src/command-parser/strip-quotes.js' {
  declare module.exports: $Exports<'concurrently/src/command-parser/strip-quotes'>;
}
declare module 'concurrently/src/command-parser/strip-quotes.spec.js' {
  declare module.exports: $Exports<'concurrently/src/command-parser/strip-quotes.spec'>;
}
declare module 'concurrently/src/command.js' {
  declare module.exports: $Exports<'concurrently/src/command'>;
}
declare module 'concurrently/src/command.spec.js' {
  declare module.exports: $Exports<'concurrently/src/command.spec'>;
}
declare module 'concurrently/src/completion-listener.js' {
  declare module.exports: $Exports<'concurrently/src/completion-listener'>;
}
declare module 'concurrently/src/completion-listener.spec.js' {
  declare module.exports: $Exports<'concurrently/src/completion-listener.spec'>;
}
declare module 'concurrently/src/concurrently.js' {
  declare module.exports: $Exports<'concurrently/src/concurrently'>;
}
declare module 'concurrently/src/concurrently.spec.js' {
  declare module.exports: $Exports<'concurrently/src/concurrently.spec'>;
}
declare module 'concurrently/src/defaults.js' {
  declare module.exports: $Exports<'concurrently/src/defaults'>;
}
declare module 'concurrently/src/flow-control/fixtures/fake-command.js' {
  declare module.exports: $Exports<'concurrently/src/flow-control/fixtures/fake-command'>;
}
declare module 'concurrently/src/flow-control/input-handler.js' {
  declare module.exports: $Exports<'concurrently/src/flow-control/input-handler'>;
}
declare module 'concurrently/src/flow-control/input-handler.spec.js' {
  declare module.exports: $Exports<'concurrently/src/flow-control/input-handler.spec'>;
}
declare module 'concurrently/src/flow-control/kill-on-signal.js' {
  declare module.exports: $Exports<'concurrently/src/flow-control/kill-on-signal'>;
}
declare module 'concurrently/src/flow-control/kill-on-signal.spec.js' {
  declare module.exports: $Exports<'concurrently/src/flow-control/kill-on-signal.spec'>;
}
declare module 'concurrently/src/flow-control/kill-others.js' {
  declare module.exports: $Exports<'concurrently/src/flow-control/kill-others'>;
}
declare module 'concurrently/src/flow-control/kill-others.spec.js' {
  declare module.exports: $Exports<'concurrently/src/flow-control/kill-others.spec'>;
}
declare module 'concurrently/src/flow-control/log-error.js' {
  declare module.exports: $Exports<'concurrently/src/flow-control/log-error'>;
}
declare module 'concurrently/src/flow-control/log-error.spec.js' {
  declare module.exports: $Exports<'concurrently/src/flow-control/log-error.spec'>;
}
declare module 'concurrently/src/flow-control/log-exit.js' {
  declare module.exports: $Exports<'concurrently/src/flow-control/log-exit'>;
}
declare module 'concurrently/src/flow-control/log-exit.spec.js' {
  declare module.exports: $Exports<'concurrently/src/flow-control/log-exit.spec'>;
}
declare module 'concurrently/src/flow-control/log-output.js' {
  declare module.exports: $Exports<'concurrently/src/flow-control/log-output'>;
}
declare module 'concurrently/src/flow-control/log-output.spec.js' {
  declare module.exports: $Exports<'concurrently/src/flow-control/log-output.spec'>;
}
declare module 'concurrently/src/flow-control/restart-process.js' {
  declare module.exports: $Exports<'concurrently/src/flow-control/restart-process'>;
}
declare module 'concurrently/src/flow-control/restart-process.spec.js' {
  declare module.exports: $Exports<'concurrently/src/flow-control/restart-process.spec'>;
}
declare module 'concurrently/src/get-spawn-opts.js' {
  declare module.exports: $Exports<'concurrently/src/get-spawn-opts'>;
}
declare module 'concurrently/src/get-spawn-opts.spec.js' {
  declare module.exports: $Exports<'concurrently/src/get-spawn-opts.spec'>;
}
declare module 'concurrently/src/logger.js' {
  declare module.exports: $Exports<'concurrently/src/logger'>;
}
declare module 'concurrently/src/logger.spec.js' {
  declare module.exports: $Exports<'concurrently/src/logger.spec'>;
}
