// flow-typed signature: 14c57d6105155f55c31bf05fa1c0c64a
// flow-typed version: <<STUB>>/connected-react-router_v^5.0.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connected-react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connected-react-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'connected-react-router/immutable' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/actions' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/ConnectedRouter' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/createAll' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/immutable' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/index' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/middleware' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/reducer' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/seamless-immutable' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/selectors' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/structure/immutable/getIn' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/structure/immutable/index' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/structure/plain/getIn' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/structure/plain/index' {
  declare module.exports: any;
}

declare module 'connected-react-router/lib/structure/seamless-immutable/index' {
  declare module.exports: any;
}

declare module 'connected-react-router/seamless-immutable' {
  declare module.exports: any;
}

declare module 'connected-react-router/umd/ConnectedReactRouter' {
  declare module.exports: any;
}

declare module 'connected-react-router/umd/ConnectedReactRouter.min' {
  declare module.exports: any;
}

declare module 'connected-react-router/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'connected-react-router/immutable.js' {
  declare module.exports: $Exports<'connected-react-router/immutable'>;
}
declare module 'connected-react-router/lib/actions.js' {
  declare module.exports: $Exports<'connected-react-router/lib/actions'>;
}
declare module 'connected-react-router/lib/ConnectedRouter.js' {
  declare module.exports: $Exports<'connected-react-router/lib/ConnectedRouter'>;
}
declare module 'connected-react-router/lib/createAll.js' {
  declare module.exports: $Exports<'connected-react-router/lib/createAll'>;
}
declare module 'connected-react-router/lib/immutable.js' {
  declare module.exports: $Exports<'connected-react-router/lib/immutable'>;
}
declare module 'connected-react-router/lib/index.js' {
  declare module.exports: $Exports<'connected-react-router/lib/index'>;
}
declare module 'connected-react-router/lib/middleware.js' {
  declare module.exports: $Exports<'connected-react-router/lib/middleware'>;
}
declare module 'connected-react-router/lib/reducer.js' {
  declare module.exports: $Exports<'connected-react-router/lib/reducer'>;
}
declare module 'connected-react-router/lib/seamless-immutable.js' {
  declare module.exports: $Exports<'connected-react-router/lib/seamless-immutable'>;
}
declare module 'connected-react-router/lib/selectors.js' {
  declare module.exports: $Exports<'connected-react-router/lib/selectors'>;
}
declare module 'connected-react-router/lib/structure/immutable/getIn.js' {
  declare module.exports: $Exports<'connected-react-router/lib/structure/immutable/getIn'>;
}
declare module 'connected-react-router/lib/structure/immutable/index.js' {
  declare module.exports: $Exports<'connected-react-router/lib/structure/immutable/index'>;
}
declare module 'connected-react-router/lib/structure/plain/getIn.js' {
  declare module.exports: $Exports<'connected-react-router/lib/structure/plain/getIn'>;
}
declare module 'connected-react-router/lib/structure/plain/index.js' {
  declare module.exports: $Exports<'connected-react-router/lib/structure/plain/index'>;
}
declare module 'connected-react-router/lib/structure/seamless-immutable/index.js' {
  declare module.exports: $Exports<'connected-react-router/lib/structure/seamless-immutable/index'>;
}
declare module 'connected-react-router/seamless-immutable.js' {
  declare module.exports: $Exports<'connected-react-router/seamless-immutable'>;
}
declare module 'connected-react-router/umd/ConnectedReactRouter.js' {
  declare module.exports: $Exports<'connected-react-router/umd/ConnectedReactRouter'>;
}
declare module 'connected-react-router/umd/ConnectedReactRouter.min.js' {
  declare module.exports: $Exports<'connected-react-router/umd/ConnectedReactRouter.min'>;
}
declare module 'connected-react-router/webpack.config.js' {
  declare module.exports: $Exports<'connected-react-router/webpack.config'>;
}
