// flow-typed signature: 6051759dab585d5f4dbf9cc81abebc15
// flow-typed version: <<STUB>>/deps_downloader_vhttps://s3.eu-west-2.amazonaws.com/deps-downloader/deps_downloader-0.1.0.tgz/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'deps_downloader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'deps_downloader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'deps_downloader/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'deps_downloader/cli.js' {
  declare module.exports: $Exports<'deps_downloader/cli'>;
}
declare module 'deps_downloader/index' {
  declare module.exports: $Exports<'deps_downloader'>;
}
declare module 'deps_downloader/index.js' {
  declare module.exports: $Exports<'deps_downloader'>;
}
