// flow-typed signature: 152ac5e5e1a1f615f5cce1c34886b0eb
// flow-typed version: <<STUB>>/electron-redux_v1.3.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-redux/dist/__mocks__/debug' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/__mocks__/electron' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/actions/__tests__/alias' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/actions/alias' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/helpers/__mocks__/validateAction' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/helpers/__tests__/createAliasedAction' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/helpers/__tests__/getInitialStateRenderer' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/helpers/__tests__/replayActionMain' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/helpers/__tests__/replayActionRenderer' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/helpers/__tests__/validateAction' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/helpers/createAliasedAction' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/helpers/getInitialStateRenderer' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/helpers/replayActionMain' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/helpers/replayActionRenderer' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/helpers/validateAction' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/index' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/middleware/__tests__/forwardToMain' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/middleware/__tests__/forwardToRenderer' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/middleware/__tests__/triggerAlias' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/middleware/forwardToMain' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/middleware/forwardToRenderer' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/middleware/triggerAlias' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/registry/__tests__/alias' {
  declare module.exports: any;
}

declare module 'electron-redux/dist/registry/alias' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-redux/dist/__mocks__/debug.js' {
  declare module.exports: $Exports<'electron-redux/dist/__mocks__/debug'>;
}
declare module 'electron-redux/dist/__mocks__/electron.js' {
  declare module.exports: $Exports<'electron-redux/dist/__mocks__/electron'>;
}
declare module 'electron-redux/dist/actions/__tests__/alias.js' {
  declare module.exports: $Exports<'electron-redux/dist/actions/__tests__/alias'>;
}
declare module 'electron-redux/dist/actions/alias.js' {
  declare module.exports: $Exports<'electron-redux/dist/actions/alias'>;
}
declare module 'electron-redux/dist/helpers/__mocks__/validateAction.js' {
  declare module.exports: $Exports<'electron-redux/dist/helpers/__mocks__/validateAction'>;
}
declare module 'electron-redux/dist/helpers/__tests__/createAliasedAction.js' {
  declare module.exports: $Exports<'electron-redux/dist/helpers/__tests__/createAliasedAction'>;
}
declare module 'electron-redux/dist/helpers/__tests__/getInitialStateRenderer.js' {
  declare module.exports: $Exports<'electron-redux/dist/helpers/__tests__/getInitialStateRenderer'>;
}
declare module 'electron-redux/dist/helpers/__tests__/replayActionMain.js' {
  declare module.exports: $Exports<'electron-redux/dist/helpers/__tests__/replayActionMain'>;
}
declare module 'electron-redux/dist/helpers/__tests__/replayActionRenderer.js' {
  declare module.exports: $Exports<'electron-redux/dist/helpers/__tests__/replayActionRenderer'>;
}
declare module 'electron-redux/dist/helpers/__tests__/validateAction.js' {
  declare module.exports: $Exports<'electron-redux/dist/helpers/__tests__/validateAction'>;
}
declare module 'electron-redux/dist/helpers/createAliasedAction.js' {
  declare module.exports: $Exports<'electron-redux/dist/helpers/createAliasedAction'>;
}
declare module 'electron-redux/dist/helpers/getInitialStateRenderer.js' {
  declare module.exports: $Exports<'electron-redux/dist/helpers/getInitialStateRenderer'>;
}
declare module 'electron-redux/dist/helpers/replayActionMain.js' {
  declare module.exports: $Exports<'electron-redux/dist/helpers/replayActionMain'>;
}
declare module 'electron-redux/dist/helpers/replayActionRenderer.js' {
  declare module.exports: $Exports<'electron-redux/dist/helpers/replayActionRenderer'>;
}
declare module 'electron-redux/dist/helpers/validateAction.js' {
  declare module.exports: $Exports<'electron-redux/dist/helpers/validateAction'>;
}
declare module 'electron-redux/dist/index.js' {
  declare module.exports: $Exports<'electron-redux/dist/index'>;
}
declare module 'electron-redux/dist/middleware/__tests__/forwardToMain.js' {
  declare module.exports: $Exports<'electron-redux/dist/middleware/__tests__/forwardToMain'>;
}
declare module 'electron-redux/dist/middleware/__tests__/forwardToRenderer.js' {
  declare module.exports: $Exports<'electron-redux/dist/middleware/__tests__/forwardToRenderer'>;
}
declare module 'electron-redux/dist/middleware/__tests__/triggerAlias.js' {
  declare module.exports: $Exports<'electron-redux/dist/middleware/__tests__/triggerAlias'>;
}
declare module 'electron-redux/dist/middleware/forwardToMain.js' {
  declare module.exports: $Exports<'electron-redux/dist/middleware/forwardToMain'>;
}
declare module 'electron-redux/dist/middleware/forwardToRenderer.js' {
  declare module.exports: $Exports<'electron-redux/dist/middleware/forwardToRenderer'>;
}
declare module 'electron-redux/dist/middleware/triggerAlias.js' {
  declare module.exports: $Exports<'electron-redux/dist/middleware/triggerAlias'>;
}
declare module 'electron-redux/dist/registry/__tests__/alias.js' {
  declare module.exports: $Exports<'electron-redux/dist/registry/__tests__/alias'>;
}
declare module 'electron-redux/dist/registry/alias.js' {
  declare module.exports: $Exports<'electron-redux/dist/registry/alias'>;
}
