// flow-typed signature: bc4992faa4b5b61afdedbebd1cbdb7c4
// flow-typed version: <<STUB>>/enum_v2.5.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enum'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enum' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'enum/dist/enum' {
  declare module.exports: any;
}

declare module 'enum/dist/enumItem' {
  declare module.exports: any;
}

declare module 'enum/dist/indexOf' {
  declare module.exports: any;
}

declare module 'enum/dist/isType' {
  declare module.exports: any;
}

declare module 'enum/enum-2.5.0' {
  declare module.exports: any;
}

declare module 'enum/enum-2.5.0.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'enum/dist/enum.js' {
  declare module.exports: $Exports<'enum/dist/enum'>;
}
declare module 'enum/dist/enumItem.js' {
  declare module.exports: $Exports<'enum/dist/enumItem'>;
}
declare module 'enum/dist/indexOf.js' {
  declare module.exports: $Exports<'enum/dist/indexOf'>;
}
declare module 'enum/dist/isType.js' {
  declare module.exports: $Exports<'enum/dist/isType'>;
}
declare module 'enum/enum-2.5.0.js' {
  declare module.exports: $Exports<'enum/enum-2.5.0'>;
}
declare module 'enum/enum-2.5.0.min.js' {
  declare module.exports: $Exports<'enum/enum-2.5.0.min'>;
}
declare module 'enum/index' {
  declare module.exports: $Exports<'enum'>;
}
declare module 'enum/index.js' {
  declare module.exports: $Exports<'enum'>;
}
