// flow-typed signature: 1d6a07050bee688650bd9e5ed75d9274
// flow-typed version: <<STUB>>/ffi_v2.3.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ffi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ffi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ffi/example/abs' {
  declare module.exports: any;
}

declare module 'ffi/example/factorial/factorial' {
  declare module.exports: any;
}

declare module 'ffi/example/sqlite' {
  declare module.exports: any;
}

declare module 'ffi/lib/_foreign_function' {
  declare module.exports: any;
}

declare module 'ffi/lib/bindings' {
  declare module.exports: any;
}

declare module 'ffi/lib/callback' {
  declare module.exports: any;
}

declare module 'ffi/lib/cif_var' {
  declare module.exports: any;
}

declare module 'ffi/lib/cif' {
  declare module.exports: any;
}

declare module 'ffi/lib/dynamic_library' {
  declare module.exports: any;
}

declare module 'ffi/lib/errno' {
  declare module.exports: any;
}

declare module 'ffi/lib/ffi' {
  declare module.exports: any;
}

declare module 'ffi/lib/foreign_function_var' {
  declare module.exports: any;
}

declare module 'ffi/lib/foreign_function' {
  declare module.exports: any;
}

declare module 'ffi/lib/function' {
  declare module.exports: any;
}

declare module 'ffi/lib/library' {
  declare module.exports: any;
}

declare module 'ffi/lib/type' {
  declare module.exports: any;
}

declare module 'ffi/test/callback' {
  declare module.exports: any;
}

declare module 'ffi/test/cif' {
  declare module.exports: any;
}

declare module 'ffi/test/dynamic_library' {
  declare module.exports: any;
}

declare module 'ffi/test/errno' {
  declare module.exports: any;
}

declare module 'ffi/test/foreign_function' {
  declare module.exports: any;
}

declare module 'ffi/test/function' {
  declare module.exports: any;
}

declare module 'ffi/test/library' {
  declare module.exports: any;
}

declare module 'ffi/test/objc' {
  declare module.exports: any;
}

declare module 'ffi/test/types' {
  declare module.exports: any;
}

declare module 'ffi/test/variadic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ffi/example/abs.js' {
  declare module.exports: $Exports<'ffi/example/abs'>;
}
declare module 'ffi/example/factorial/factorial.js' {
  declare module.exports: $Exports<'ffi/example/factorial/factorial'>;
}
declare module 'ffi/example/sqlite.js' {
  declare module.exports: $Exports<'ffi/example/sqlite'>;
}
declare module 'ffi/lib/_foreign_function.js' {
  declare module.exports: $Exports<'ffi/lib/_foreign_function'>;
}
declare module 'ffi/lib/bindings.js' {
  declare module.exports: $Exports<'ffi/lib/bindings'>;
}
declare module 'ffi/lib/callback.js' {
  declare module.exports: $Exports<'ffi/lib/callback'>;
}
declare module 'ffi/lib/cif_var.js' {
  declare module.exports: $Exports<'ffi/lib/cif_var'>;
}
declare module 'ffi/lib/cif.js' {
  declare module.exports: $Exports<'ffi/lib/cif'>;
}
declare module 'ffi/lib/dynamic_library.js' {
  declare module.exports: $Exports<'ffi/lib/dynamic_library'>;
}
declare module 'ffi/lib/errno.js' {
  declare module.exports: $Exports<'ffi/lib/errno'>;
}
declare module 'ffi/lib/ffi.js' {
  declare module.exports: $Exports<'ffi/lib/ffi'>;
}
declare module 'ffi/lib/foreign_function_var.js' {
  declare module.exports: $Exports<'ffi/lib/foreign_function_var'>;
}
declare module 'ffi/lib/foreign_function.js' {
  declare module.exports: $Exports<'ffi/lib/foreign_function'>;
}
declare module 'ffi/lib/function.js' {
  declare module.exports: $Exports<'ffi/lib/function'>;
}
declare module 'ffi/lib/library.js' {
  declare module.exports: $Exports<'ffi/lib/library'>;
}
declare module 'ffi/lib/type.js' {
  declare module.exports: $Exports<'ffi/lib/type'>;
}
declare module 'ffi/test/callback.js' {
  declare module.exports: $Exports<'ffi/test/callback'>;
}
declare module 'ffi/test/cif.js' {
  declare module.exports: $Exports<'ffi/test/cif'>;
}
declare module 'ffi/test/dynamic_library.js' {
  declare module.exports: $Exports<'ffi/test/dynamic_library'>;
}
declare module 'ffi/test/errno.js' {
  declare module.exports: $Exports<'ffi/test/errno'>;
}
declare module 'ffi/test/foreign_function.js' {
  declare module.exports: $Exports<'ffi/test/foreign_function'>;
}
declare module 'ffi/test/function.js' {
  declare module.exports: $Exports<'ffi/test/function'>;
}
declare module 'ffi/test/library.js' {
  declare module.exports: $Exports<'ffi/test/library'>;
}
declare module 'ffi/test/objc.js' {
  declare module.exports: $Exports<'ffi/test/objc'>;
}
declare module 'ffi/test/types.js' {
  declare module.exports: $Exports<'ffi/test/types'>;
}
declare module 'ffi/test/variadic.js' {
  declare module.exports: $Exports<'ffi/test/variadic'>;
}
