// flow-typed signature: 3b8c693b1f032f8bc8573608e01e9c29
// flow-typed version: <<STUB>>/i18n_v0.8.3/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18n'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18n' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18n/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'i18n/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'i18n/i18n' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18n/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'i18n/coverage/lcov-report/prettify'>;
}
declare module 'i18n/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'i18n/coverage/lcov-report/sorter'>;
}
declare module 'i18n/i18n.js' {
  declare module.exports: $Exports<'i18n/i18n'>;
}
declare module 'i18n/index' {
  declare module.exports: $Exports<'i18n'>;
}
declare module 'i18n/index.js' {
  declare module.exports: $Exports<'i18n'>;
}
