// flow-typed signature: a2a52e87d3567d352e608a68fded3b55
// flow-typed version: <<STUB>>/jest-tobetype_vgit+https://github.com/joshuef/jest-tobetype.git#master/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-tobetype'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-tobetype' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-tobetype/__tests__/test' {
  declare module.exports: any;
}

declare module 'jest-tobetype/index-cjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-tobetype/__tests__/test.js' {
  declare module.exports: $Exports<'jest-tobetype/__tests__/test'>;
}
declare module 'jest-tobetype/index-cjs.js' {
  declare module.exports: $Exports<'jest-tobetype/index-cjs'>;
}
declare module 'jest-tobetype/index' {
  declare module.exports: $Exports<'jest-tobetype'>;
}
declare module 'jest-tobetype/index.js' {
  declare module.exports: $Exports<'jest-tobetype'>;
}
