// flow-typed signature: e26372e163c5402e6c4b1d3fd24d03c2
// flow-typed version: <<STUB>>/nessie-ui_v6.1.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nessie-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nessie-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nessie-ui/cfg/base' {
  declare module.exports: any;
}

declare module 'nessie-ui/cfg/dev' {
  declare module.exports: any;
}

declare module 'nessie-ui/cfg/dist' {
  declare module.exports: any;
}

declare module 'nessie-ui/cfg/jest.config' {
  declare module.exports: any;
}

declare module 'nessie-ui/deployLN' {
  declare module.exports: any;
}

declare module 'nessie-ui/dist/addons' {
  declare module.exports: any;
}

declare module 'nessie-ui/dist/componentDriver' {
  declare module.exports: any;
}

declare module 'nessie-ui/dist/css' {
  declare module.exports: any;
}

declare module 'nessie-ui/dist/displayComponents' {
  declare module.exports: any;
}

declare module 'nessie-ui/dist/driverSuite' {
  declare module.exports: any;
}

declare module 'nessie-ui/dist/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/docs/assets/app' {
  declare module.exports: any;
}

declare module 'nessie-ui/docs/displayComponents' {
  declare module.exports: any;
}

declare module 'nessie-ui/postcss.config' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/addons' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Animate/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Animate/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Button/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Button/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Button/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/CheckableGroup/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/CheckableGroup/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/CheckableGroup/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Checkbox/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Checkbox/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Checkbox/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/CheckboxGroup/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/CheckboxGroup/utils' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/CodeEditor/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/CodeEditor/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/CodeEditor/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Column/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Column/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ComboBox/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ComboBox/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ComboBox/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ComboBox/utils' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/DatePicker/DatePickerHeader' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/DatePicker/DatePickerItem' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/DatePicker/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/DatePicker/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/DatePicker/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/DatePicker/TimeInput' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/DateTimeInput/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/DateTimeInput/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/DateTimeInput/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/DimensionsInput/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/DimensionsInput/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Divider/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Divider/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/DragNDrop/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/DragNDrop/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/drivers' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Dropdown/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Dropdown/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Dropdown/withDropdown' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Fieldset/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Fieldset/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/FlounderDropdown/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/FlounderDropdown/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/FlounderDropdown/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/FlounderDropdown/utils' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Form/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Form/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Form/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Grid/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Grid/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Grid/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/H1/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/H1/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/H2/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/H2/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/H3/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/H3/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/H4/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/H4/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Icon/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Icon/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Icon/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/IconButton/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/IconButton/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/IconWithTooltip/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/IconWithTooltip/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/IconWithTooltip/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/InputField/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/InputField/InputFrame' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/InputField/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Label/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Label/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ListBox/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ListBox/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ListBox/ListBoxOption' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ListBox/ListBoxOptionGroup' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ListBox/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ListBox/utils' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/MessageBox/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/MessageBox/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ModalDialog/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ModalDialog/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ModalDialog/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Module/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Module/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Module/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/NavBar/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/NavBar/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/NavDropdown/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/NavDropdown/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/NavItem/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/NavItem/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/NavItem/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/NavList/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/NavList/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/NessieLogo/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/NotificationBar/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/NotificationBar/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/NotificationBar/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Page/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/PageContent/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/PageContentHeader/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/PageFooter/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/PageHeader/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Paginator/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Paginator/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Paginator/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/PasswordInput/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/PasswordInput/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/PasswordInput/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ProgressBar/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ProgressBar/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ProgressIndicator/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ProgressIndicator/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/proto/Checkable' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/proto/InputContainer' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/proto/withInputContainer' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Radio/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Radio/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/RadioGroup/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/RadioGroup/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/RadioGroup/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/RadioGroup/utils' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Required/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Required/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Row/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ScrollBar/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ScrollBar/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ScrollBar/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ScrollBox/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ScrollBox/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ScrollBox/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ScrollBox/utils' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Section/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Section/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Section/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Slider/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Slider/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Slider/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/SliderGroup/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/SliderGroup/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/SliderGroup/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Sorter/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Sorter/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Sorter/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Spinner/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Spinner/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/SpriteMap/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/SpriteMap/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/StatusIndicator/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/StatusIndicator/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Switch/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Switch/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Switch/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Tab/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/TabButton/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/TabButton/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/TabButton/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Table/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Table/utils' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/TableCell/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/TableRow/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Tabs/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Tabs/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Tabs/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Tag/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Tag/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Tag/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/TagInput/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/TagInput/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/TagInput/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/TagInput/utils' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Testing/CommonDrivers/clickableComponentDriver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Testing/CommonDrivers/inputComponentDriver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Testing/CommonDrivers/simpleComponentDriver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Testing/CommonDrivers/wrapperDriver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Testing/ComponentDriver/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Testing/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Testing/mocks/fileMock' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Testing/mocks/styleMock' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Testing/setupTestEnvironment' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Testing/setupTestFramework' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Text/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Text/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Text/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Text/utils' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/TextArea/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/TextArea/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/TextArea/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/TextInput/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/TextInput/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/TextInputWithDropdown/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/TextInputWithDropdown/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/TextInputWithIcon/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/TextInputWithIcon/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/TextInputWithIcon/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ToggleButton/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ToggleButton/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Tooltip/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Tooltip/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Tooltip/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Uploader/driver' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Uploader/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/Uploader/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/utils/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/utils/withSticky/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ValuedTextInput/index' {
  declare module.exports: any;
}

declare module 'nessie-ui/src/ValuedTextInput/tests' {
  declare module.exports: any;
}

declare module 'nessie-ui/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nessie-ui/cfg/base.js' {
  declare module.exports: $Exports<'nessie-ui/cfg/base'>;
}
declare module 'nessie-ui/cfg/dev.js' {
  declare module.exports: $Exports<'nessie-ui/cfg/dev'>;
}
declare module 'nessie-ui/cfg/dist.js' {
  declare module.exports: $Exports<'nessie-ui/cfg/dist'>;
}
declare module 'nessie-ui/cfg/jest.config.js' {
  declare module.exports: $Exports<'nessie-ui/cfg/jest.config'>;
}
declare module 'nessie-ui/deployLN.js' {
  declare module.exports: $Exports<'nessie-ui/deployLN'>;
}
declare module 'nessie-ui/dist/addons.js' {
  declare module.exports: $Exports<'nessie-ui/dist/addons'>;
}
declare module 'nessie-ui/dist/componentDriver.js' {
  declare module.exports: $Exports<'nessie-ui/dist/componentDriver'>;
}
declare module 'nessie-ui/dist/css.js' {
  declare module.exports: $Exports<'nessie-ui/dist/css'>;
}
declare module 'nessie-ui/dist/displayComponents.js' {
  declare module.exports: $Exports<'nessie-ui/dist/displayComponents'>;
}
declare module 'nessie-ui/dist/driverSuite.js' {
  declare module.exports: $Exports<'nessie-ui/dist/driverSuite'>;
}
declare module 'nessie-ui/dist/index.js' {
  declare module.exports: $Exports<'nessie-ui/dist/index'>;
}
declare module 'nessie-ui/docs/assets/app.js' {
  declare module.exports: $Exports<'nessie-ui/docs/assets/app'>;
}
declare module 'nessie-ui/docs/displayComponents.js' {
  declare module.exports: $Exports<'nessie-ui/docs/displayComponents'>;
}
declare module 'nessie-ui/postcss.config.js' {
  declare module.exports: $Exports<'nessie-ui/postcss.config'>;
}
declare module 'nessie-ui/src/addons.js' {
  declare module.exports: $Exports<'nessie-ui/src/addons'>;
}
declare module 'nessie-ui/src/Animate/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Animate/index'>;
}
declare module 'nessie-ui/src/Animate/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Animate/tests'>;
}
declare module 'nessie-ui/src/Button/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/Button/driver'>;
}
declare module 'nessie-ui/src/Button/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Button/index'>;
}
declare module 'nessie-ui/src/Button/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Button/tests'>;
}
declare module 'nessie-ui/src/CheckableGroup/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/CheckableGroup/driver'>;
}
declare module 'nessie-ui/src/CheckableGroup/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/CheckableGroup/index'>;
}
declare module 'nessie-ui/src/CheckableGroup/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/CheckableGroup/tests'>;
}
declare module 'nessie-ui/src/Checkbox/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/Checkbox/driver'>;
}
declare module 'nessie-ui/src/Checkbox/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Checkbox/index'>;
}
declare module 'nessie-ui/src/Checkbox/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Checkbox/tests'>;
}
declare module 'nessie-ui/src/CheckboxGroup/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/CheckboxGroup/index'>;
}
declare module 'nessie-ui/src/CheckboxGroup/utils.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/CheckboxGroup/utils'>;
}
declare module 'nessie-ui/src/CodeEditor/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/CodeEditor/driver'>;
}
declare module 'nessie-ui/src/CodeEditor/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/CodeEditor/index'>;
}
declare module 'nessie-ui/src/CodeEditor/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/CodeEditor/tests'>;
}
declare module 'nessie-ui/src/Column/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Column/index'>;
}
declare module 'nessie-ui/src/Column/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Column/tests'>;
}
declare module 'nessie-ui/src/ComboBox/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/ComboBox/driver'>;
}
declare module 'nessie-ui/src/ComboBox/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ComboBox/index'>;
}
declare module 'nessie-ui/src/ComboBox/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ComboBox/tests'>;
}
declare module 'nessie-ui/src/ComboBox/utils.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ComboBox/utils'>;
}
declare module 'nessie-ui/src/DatePicker/DatePickerHeader.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/DatePicker/DatePickerHeader'>;
}
declare module 'nessie-ui/src/DatePicker/DatePickerItem.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/DatePicker/DatePickerItem'>;
}
declare module 'nessie-ui/src/DatePicker/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/DatePicker/driver'>;
}
declare module 'nessie-ui/src/DatePicker/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/DatePicker/index'>;
}
declare module 'nessie-ui/src/DatePicker/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/DatePicker/tests'>;
}
declare module 'nessie-ui/src/DatePicker/TimeInput.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/DatePicker/TimeInput'>;
}
declare module 'nessie-ui/src/DateTimeInput/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/DateTimeInput/driver'>;
}
declare module 'nessie-ui/src/DateTimeInput/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/DateTimeInput/index'>;
}
declare module 'nessie-ui/src/DateTimeInput/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/DateTimeInput/tests'>;
}
declare module 'nessie-ui/src/DimensionsInput/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/DimensionsInput/index'>;
}
declare module 'nessie-ui/src/DimensionsInput/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/DimensionsInput/tests'>;
}
declare module 'nessie-ui/src/Divider/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Divider/index'>;
}
declare module 'nessie-ui/src/Divider/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Divider/tests'>;
}
declare module 'nessie-ui/src/DragNDrop/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/DragNDrop/index'>;
}
declare module 'nessie-ui/src/DragNDrop/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/DragNDrop/tests'>;
}
declare module 'nessie-ui/src/drivers.js' {
  declare module.exports: $Exports<'nessie-ui/src/drivers'>;
}
declare module 'nessie-ui/src/Dropdown/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Dropdown/index'>;
}
declare module 'nessie-ui/src/Dropdown/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Dropdown/tests'>;
}
declare module 'nessie-ui/src/Dropdown/withDropdown.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Dropdown/withDropdown'>;
}
declare module 'nessie-ui/src/Fieldset/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Fieldset/index'>;
}
declare module 'nessie-ui/src/Fieldset/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Fieldset/tests'>;
}
declare module 'nessie-ui/src/FlounderDropdown/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/FlounderDropdown/driver'>;
}
declare module 'nessie-ui/src/FlounderDropdown/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/FlounderDropdown/index'>;
}
declare module 'nessie-ui/src/FlounderDropdown/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/FlounderDropdown/tests'>;
}
declare module 'nessie-ui/src/FlounderDropdown/utils.js' {
  declare module.exports: $Exports<'nessie-ui/src/FlounderDropdown/utils'>;
}
declare module 'nessie-ui/src/Form/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/Form/driver'>;
}
declare module 'nessie-ui/src/Form/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Form/index'>;
}
declare module 'nessie-ui/src/Form/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Form/tests'>;
}
declare module 'nessie-ui/src/Grid/driver.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Grid/driver'>;
}
declare module 'nessie-ui/src/Grid/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Grid/index'>;
}
declare module 'nessie-ui/src/Grid/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Grid/tests'>;
}
declare module 'nessie-ui/src/H1/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/H1/index'>;
}
declare module 'nessie-ui/src/H1/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/H1/tests'>;
}
declare module 'nessie-ui/src/H2/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/H2/index'>;
}
declare module 'nessie-ui/src/H2/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/H2/tests'>;
}
declare module 'nessie-ui/src/H3/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/H3/index'>;
}
declare module 'nessie-ui/src/H3/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/H3/tests'>;
}
declare module 'nessie-ui/src/H4/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/H4/index'>;
}
declare module 'nessie-ui/src/H4/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/H4/tests'>;
}
declare module 'nessie-ui/src/Icon/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/Icon/driver'>;
}
declare module 'nessie-ui/src/Icon/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Icon/index'>;
}
declare module 'nessie-ui/src/Icon/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Icon/tests'>;
}
declare module 'nessie-ui/src/IconButton/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/IconButton/index'>;
}
declare module 'nessie-ui/src/IconButton/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/IconButton/tests'>;
}
declare module 'nessie-ui/src/IconWithTooltip/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/IconWithTooltip/driver'>;
}
declare module 'nessie-ui/src/IconWithTooltip/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/IconWithTooltip/index'>;
}
declare module 'nessie-ui/src/IconWithTooltip/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/IconWithTooltip/tests'>;
}
declare module 'nessie-ui/src/index.js' {
  declare module.exports: $Exports<'nessie-ui/src/index'>;
}
declare module 'nessie-ui/src/InputField/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/InputField/index'>;
}
declare module 'nessie-ui/src/InputField/InputFrame.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/InputField/InputFrame'>;
}
declare module 'nessie-ui/src/InputField/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/InputField/tests'>;
}
declare module 'nessie-ui/src/Label/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Label/index'>;
}
declare module 'nessie-ui/src/Label/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Label/tests'>;
}
declare module 'nessie-ui/src/ListBox/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/ListBox/driver'>;
}
declare module 'nessie-ui/src/ListBox/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ListBox/index'>;
}
declare module 'nessie-ui/src/ListBox/ListBoxOption.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ListBox/ListBoxOption'>;
}
declare module 'nessie-ui/src/ListBox/ListBoxOptionGroup.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ListBox/ListBoxOptionGroup'>;
}
declare module 'nessie-ui/src/ListBox/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ListBox/tests'>;
}
declare module 'nessie-ui/src/ListBox/utils.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ListBox/utils'>;
}
declare module 'nessie-ui/src/MessageBox/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/MessageBox/index'>;
}
declare module 'nessie-ui/src/MessageBox/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/MessageBox/tests'>;
}
declare module 'nessie-ui/src/ModalDialog/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/ModalDialog/driver'>;
}
declare module 'nessie-ui/src/ModalDialog/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ModalDialog/index'>;
}
declare module 'nessie-ui/src/ModalDialog/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ModalDialog/tests'>;
}
declare module 'nessie-ui/src/Module/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/Module/driver'>;
}
declare module 'nessie-ui/src/Module/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Module/index'>;
}
declare module 'nessie-ui/src/Module/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Module/tests'>;
}
declare module 'nessie-ui/src/NavBar/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/NavBar/index'>;
}
declare module 'nessie-ui/src/NavBar/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/NavBar/tests'>;
}
declare module 'nessie-ui/src/NavDropdown/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/NavDropdown/index'>;
}
declare module 'nessie-ui/src/NavDropdown/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/NavDropdown/tests'>;
}
declare module 'nessie-ui/src/NavItem/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/NavItem/driver'>;
}
declare module 'nessie-ui/src/NavItem/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/NavItem/index'>;
}
declare module 'nessie-ui/src/NavItem/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/NavItem/tests'>;
}
declare module 'nessie-ui/src/NavList/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/NavList/index'>;
}
declare module 'nessie-ui/src/NavList/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/NavList/tests'>;
}
declare module 'nessie-ui/src/NessieLogo/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/NessieLogo/index'>;
}
declare module 'nessie-ui/src/NotificationBar/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/NotificationBar/driver'>;
}
declare module 'nessie-ui/src/NotificationBar/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/NotificationBar/index'>;
}
declare module 'nessie-ui/src/NotificationBar/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/NotificationBar/tests'>;
}
declare module 'nessie-ui/src/Page/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Page/index'>;
}
declare module 'nessie-ui/src/PageContent/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/PageContent/index'>;
}
declare module 'nessie-ui/src/PageContentHeader/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/PageContentHeader/index'>;
}
declare module 'nessie-ui/src/PageFooter/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/PageFooter/index'>;
}
declare module 'nessie-ui/src/PageHeader/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/PageHeader/index'>;
}
declare module 'nessie-ui/src/Paginator/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/Paginator/driver'>;
}
declare module 'nessie-ui/src/Paginator/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Paginator/index'>;
}
declare module 'nessie-ui/src/Paginator/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Paginator/tests'>;
}
declare module 'nessie-ui/src/PasswordInput/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/PasswordInput/driver'>;
}
declare module 'nessie-ui/src/PasswordInput/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/PasswordInput/index'>;
}
declare module 'nessie-ui/src/PasswordInput/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/PasswordInput/tests'>;
}
declare module 'nessie-ui/src/ProgressBar/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ProgressBar/index'>;
}
declare module 'nessie-ui/src/ProgressBar/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ProgressBar/tests'>;
}
declare module 'nessie-ui/src/ProgressIndicator/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ProgressIndicator/index'>;
}
declare module 'nessie-ui/src/ProgressIndicator/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ProgressIndicator/tests'>;
}
declare module 'nessie-ui/src/proto/Checkable.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/proto/Checkable'>;
}
declare module 'nessie-ui/src/proto/InputContainer.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/proto/InputContainer'>;
}
declare module 'nessie-ui/src/proto/withInputContainer.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/proto/withInputContainer'>;
}
declare module 'nessie-ui/src/Radio/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Radio/index'>;
}
declare module 'nessie-ui/src/Radio/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Radio/tests'>;
}
declare module 'nessie-ui/src/RadioGroup/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/RadioGroup/driver'>;
}
declare module 'nessie-ui/src/RadioGroup/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/RadioGroup/index'>;
}
declare module 'nessie-ui/src/RadioGroup/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/RadioGroup/tests'>;
}
declare module 'nessie-ui/src/RadioGroup/utils.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/RadioGroup/utils'>;
}
declare module 'nessie-ui/src/Required/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Required/index'>;
}
declare module 'nessie-ui/src/Required/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Required/tests'>;
}
declare module 'nessie-ui/src/Row/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Row/index'>;
}
declare module 'nessie-ui/src/ScrollBar/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/ScrollBar/driver'>;
}
declare module 'nessie-ui/src/ScrollBar/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ScrollBar/index'>;
}
declare module 'nessie-ui/src/ScrollBar/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ScrollBar/tests'>;
}
declare module 'nessie-ui/src/ScrollBox/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/ScrollBox/driver'>;
}
declare module 'nessie-ui/src/ScrollBox/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ScrollBox/index'>;
}
declare module 'nessie-ui/src/ScrollBox/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ScrollBox/tests'>;
}
declare module 'nessie-ui/src/ScrollBox/utils.js' {
  declare module.exports: $Exports<'nessie-ui/src/ScrollBox/utils'>;
}
declare module 'nessie-ui/src/Section/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/Section/driver'>;
}
declare module 'nessie-ui/src/Section/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Section/index'>;
}
declare module 'nessie-ui/src/Section/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Section/tests'>;
}
declare module 'nessie-ui/src/Slider/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/Slider/driver'>;
}
declare module 'nessie-ui/src/Slider/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Slider/index'>;
}
declare module 'nessie-ui/src/Slider/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Slider/tests'>;
}
declare module 'nessie-ui/src/SliderGroup/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/SliderGroup/driver'>;
}
declare module 'nessie-ui/src/SliderGroup/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/SliderGroup/index'>;
}
declare module 'nessie-ui/src/SliderGroup/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/SliderGroup/tests'>;
}
declare module 'nessie-ui/src/Sorter/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/Sorter/driver'>;
}
declare module 'nessie-ui/src/Sorter/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Sorter/index'>;
}
declare module 'nessie-ui/src/Sorter/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Sorter/tests'>;
}
declare module 'nessie-ui/src/Spinner/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Spinner/index'>;
}
declare module 'nessie-ui/src/Spinner/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Spinner/tests'>;
}
declare module 'nessie-ui/src/SpriteMap/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/SpriteMap/index'>;
}
declare module 'nessie-ui/src/SpriteMap/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/SpriteMap/tests'>;
}
declare module 'nessie-ui/src/StatusIndicator/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/StatusIndicator/index'>;
}
declare module 'nessie-ui/src/StatusIndicator/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/StatusIndicator/tests'>;
}
declare module 'nessie-ui/src/Switch/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/Switch/driver'>;
}
declare module 'nessie-ui/src/Switch/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Switch/index'>;
}
declare module 'nessie-ui/src/Switch/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Switch/tests'>;
}
declare module 'nessie-ui/src/Tab/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Tab/index'>;
}
declare module 'nessie-ui/src/TabButton/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/TabButton/driver'>;
}
declare module 'nessie-ui/src/TabButton/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/TabButton/index'>;
}
declare module 'nessie-ui/src/TabButton/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/TabButton/tests'>;
}
declare module 'nessie-ui/src/Table/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Table/index'>;
}
declare module 'nessie-ui/src/Table/utils.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Table/utils'>;
}
declare module 'nessie-ui/src/TableCell/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/TableCell/index'>;
}
declare module 'nessie-ui/src/TableRow/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/TableRow/index'>;
}
declare module 'nessie-ui/src/Tabs/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/Tabs/driver'>;
}
declare module 'nessie-ui/src/Tabs/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Tabs/index'>;
}
declare module 'nessie-ui/src/Tabs/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Tabs/tests'>;
}
declare module 'nessie-ui/src/Tag/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/Tag/driver'>;
}
declare module 'nessie-ui/src/Tag/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Tag/index'>;
}
declare module 'nessie-ui/src/Tag/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Tag/tests'>;
}
declare module 'nessie-ui/src/TagInput/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/TagInput/driver'>;
}
declare module 'nessie-ui/src/TagInput/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/TagInput/index'>;
}
declare module 'nessie-ui/src/TagInput/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/TagInput/tests'>;
}
declare module 'nessie-ui/src/TagInput/utils.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/TagInput/utils'>;
}
declare module 'nessie-ui/src/Testing/CommonDrivers/clickableComponentDriver.js' {
  declare module.exports: $Exports<'nessie-ui/src/Testing/CommonDrivers/clickableComponentDriver'>;
}
declare module 'nessie-ui/src/Testing/CommonDrivers/inputComponentDriver.js' {
  declare module.exports: $Exports<'nessie-ui/src/Testing/CommonDrivers/inputComponentDriver'>;
}
declare module 'nessie-ui/src/Testing/CommonDrivers/simpleComponentDriver.js' {
  declare module.exports: $Exports<'nessie-ui/src/Testing/CommonDrivers/simpleComponentDriver'>;
}
declare module 'nessie-ui/src/Testing/CommonDrivers/wrapperDriver.js' {
  declare module.exports: $Exports<'nessie-ui/src/Testing/CommonDrivers/wrapperDriver'>;
}
declare module 'nessie-ui/src/Testing/ComponentDriver/index.js' {
  declare module.exports: $Exports<'nessie-ui/src/Testing/ComponentDriver/index'>;
}
declare module 'nessie-ui/src/Testing/index.js' {
  declare module.exports: $Exports<'nessie-ui/src/Testing/index'>;
}
declare module 'nessie-ui/src/Testing/mocks/fileMock.js' {
  declare module.exports: $Exports<'nessie-ui/src/Testing/mocks/fileMock'>;
}
declare module 'nessie-ui/src/Testing/mocks/styleMock.js' {
  declare module.exports: $Exports<'nessie-ui/src/Testing/mocks/styleMock'>;
}
declare module 'nessie-ui/src/Testing/setupTestEnvironment.js' {
  declare module.exports: $Exports<'nessie-ui/src/Testing/setupTestEnvironment'>;
}
declare module 'nessie-ui/src/Testing/setupTestFramework.js' {
  declare module.exports: $Exports<'nessie-ui/src/Testing/setupTestFramework'>;
}
declare module 'nessie-ui/src/Text/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/Text/driver'>;
}
declare module 'nessie-ui/src/Text/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Text/index'>;
}
declare module 'nessie-ui/src/Text/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Text/tests'>;
}
declare module 'nessie-ui/src/Text/utils.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Text/utils'>;
}
declare module 'nessie-ui/src/TextArea/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/TextArea/driver'>;
}
declare module 'nessie-ui/src/TextArea/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/TextArea/index'>;
}
declare module 'nessie-ui/src/TextArea/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/TextArea/tests'>;
}
declare module 'nessie-ui/src/TextInput/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/TextInput/index'>;
}
declare module 'nessie-ui/src/TextInput/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/TextInput/tests'>;
}
declare module 'nessie-ui/src/TextInputWithDropdown/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/TextInputWithDropdown/index'>;
}
declare module 'nessie-ui/src/TextInputWithDropdown/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/TextInputWithDropdown/tests'>;
}
declare module 'nessie-ui/src/TextInputWithIcon/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/TextInputWithIcon/driver'>;
}
declare module 'nessie-ui/src/TextInputWithIcon/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/TextInputWithIcon/index'>;
}
declare module 'nessie-ui/src/TextInputWithIcon/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/TextInputWithIcon/tests'>;
}
declare module 'nessie-ui/src/ToggleButton/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ToggleButton/index'>;
}
declare module 'nessie-ui/src/ToggleButton/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ToggleButton/tests'>;
}
declare module 'nessie-ui/src/Tooltip/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/Tooltip/driver'>;
}
declare module 'nessie-ui/src/Tooltip/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Tooltip/index'>;
}
declare module 'nessie-ui/src/Tooltip/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Tooltip/tests'>;
}
declare module 'nessie-ui/src/Uploader/driver.js' {
  declare module.exports: $Exports<'nessie-ui/src/Uploader/driver'>;
}
declare module 'nessie-ui/src/Uploader/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Uploader/index'>;
}
declare module 'nessie-ui/src/Uploader/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/Uploader/tests'>;
}
declare module 'nessie-ui/src/utils/index.js' {
  declare module.exports: $Exports<'nessie-ui/src/utils/index'>;
}
declare module 'nessie-ui/src/utils/withSticky/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/utils/withSticky/index'>;
}
declare module 'nessie-ui/src/ValuedTextInput/index.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ValuedTextInput/index'>;
}
declare module 'nessie-ui/src/ValuedTextInput/tests.jsx' {
  declare module.exports: $Exports<'nessie-ui/src/ValuedTextInput/tests'>;
}
declare module 'nessie-ui/webpack.config.js' {
  declare module.exports: $Exports<'nessie-ui/webpack.config'>;
}
