// flow-typed signature: 427892bebad2acba7ef5dd482f5f2c62
// flow-typed version: <<STUB>>/opencollective-postinstall_v^2.0.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opencollective-postinstall'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'opencollective-postinstall' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'opencollective-postinstall/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'opencollective-postinstall/index' {
  declare module.exports: $Exports<'opencollective-postinstall'>;
}
declare module 'opencollective-postinstall/index.js' {
  declare module.exports: $Exports<'opencollective-postinstall'>;
}
declare module 'opencollective-postinstall/index.test.js' {
  declare module.exports: $Exports<'opencollective-postinstall/index.test'>;
}
