// flow-typed signature: 93c33ace7b105583584e8e017a5802bc
// flow-typed version: <<STUB>>/postcss-scss_v^1.0.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-scss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-scss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-scss/lib/nested-declaration' {
  declare module.exports: any;
}

declare module 'postcss-scss/lib/scss-parse' {
  declare module.exports: any;
}

declare module 'postcss-scss/lib/scss-parser' {
  declare module.exports: any;
}

declare module 'postcss-scss/lib/scss-stringifier' {
  declare module.exports: any;
}

declare module 'postcss-scss/lib/scss-stringify' {
  declare module.exports: any;
}

declare module 'postcss-scss/lib/scss-syntax' {
  declare module.exports: any;
}

declare module 'postcss-scss/lib/scss-tokenize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-scss/lib/nested-declaration.js' {
  declare module.exports: $Exports<'postcss-scss/lib/nested-declaration'>;
}
declare module 'postcss-scss/lib/scss-parse.js' {
  declare module.exports: $Exports<'postcss-scss/lib/scss-parse'>;
}
declare module 'postcss-scss/lib/scss-parser.js' {
  declare module.exports: $Exports<'postcss-scss/lib/scss-parser'>;
}
declare module 'postcss-scss/lib/scss-stringifier.js' {
  declare module.exports: $Exports<'postcss-scss/lib/scss-stringifier'>;
}
declare module 'postcss-scss/lib/scss-stringify.js' {
  declare module.exports: $Exports<'postcss-scss/lib/scss-stringify'>;
}
declare module 'postcss-scss/lib/scss-syntax.js' {
  declare module.exports: $Exports<'postcss-scss/lib/scss-syntax'>;
}
declare module 'postcss-scss/lib/scss-tokenize.js' {
  declare module.exports: $Exports<'postcss-scss/lib/scss-tokenize'>;
}
