// flow-typed signature: 2be5cb19d5ecb7bd7a5a8a5dca36f42c
// flow-typed version: <<STUB>>/ref-array_v1.2.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ref-array'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ref-array' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ref-array/lib/array' {
  declare module.exports: any;
}

declare module 'ref-array/test/array' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ref-array/lib/array.js' {
  declare module.exports: $Exports<'ref-array/lib/array'>;
}
declare module 'ref-array/test/array.js' {
  declare module.exports: $Exports<'ref-array/test/array'>;
}
