// flow-typed signature: 1e3b3ba1dece39816123f044e26160fe
// flow-typed version: <<STUB>>/ref-struct_v1.1.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ref-struct'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ref-struct' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ref-struct/lib/struct' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ref-struct/lib/struct.js' {
  declare module.exports: $Exports<'ref-struct/lib/struct'>;
}
