// flow-typed signature: f2468d5b6de88a9e81f4d9f42c242e21
// flow-typed version: <<STUB>>/ref_v1.3.5/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ref'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ref' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ref/docs/compile' {
  declare module.exports: any;
}

declare module 'ref/docs/scripts/jquery-1.7.2.min' {
  declare module.exports: any;
}

declare module 'ref/docs/scripts/main' {
  declare module.exports: any;
}

declare module 'ref/lib/ref' {
  declare module.exports: any;
}

declare module 'ref/test/address' {
  declare module.exports: any;
}

declare module 'ref/test/alloc' {
  declare module.exports: any;
}

declare module 'ref/test/bool' {
  declare module.exports: any;
}

declare module 'ref/test/char' {
  declare module.exports: any;
}

declare module 'ref/test/coerce' {
  declare module.exports: any;
}

declare module 'ref/test/int64' {
  declare module.exports: any;
}

declare module 'ref/test/iojs3issue' {
  declare module.exports: any;
}

declare module 'ref/test/isNull' {
  declare module.exports: any;
}

declare module 'ref/test/object' {
  declare module.exports: any;
}

declare module 'ref/test/pointer' {
  declare module.exports: any;
}

declare module 'ref/test/ref-deref' {
  declare module.exports: any;
}

declare module 'ref/test/reinterpret' {
  declare module.exports: any;
}

declare module 'ref/test/reinterpretUntilZeros' {
  declare module.exports: any;
}

declare module 'ref/test/string' {
  declare module.exports: any;
}

declare module 'ref/test/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ref/docs/compile.js' {
  declare module.exports: $Exports<'ref/docs/compile'>;
}
declare module 'ref/docs/scripts/jquery-1.7.2.min.js' {
  declare module.exports: $Exports<'ref/docs/scripts/jquery-1.7.2.min'>;
}
declare module 'ref/docs/scripts/main.js' {
  declare module.exports: $Exports<'ref/docs/scripts/main'>;
}
declare module 'ref/lib/ref.js' {
  declare module.exports: $Exports<'ref/lib/ref'>;
}
declare module 'ref/test/address.js' {
  declare module.exports: $Exports<'ref/test/address'>;
}
declare module 'ref/test/alloc.js' {
  declare module.exports: $Exports<'ref/test/alloc'>;
}
declare module 'ref/test/bool.js' {
  declare module.exports: $Exports<'ref/test/bool'>;
}
declare module 'ref/test/char.js' {
  declare module.exports: $Exports<'ref/test/char'>;
}
declare module 'ref/test/coerce.js' {
  declare module.exports: $Exports<'ref/test/coerce'>;
}
declare module 'ref/test/int64.js' {
  declare module.exports: $Exports<'ref/test/int64'>;
}
declare module 'ref/test/iojs3issue.js' {
  declare module.exports: $Exports<'ref/test/iojs3issue'>;
}
declare module 'ref/test/isNull.js' {
  declare module.exports: $Exports<'ref/test/isNull'>;
}
declare module 'ref/test/object.js' {
  declare module.exports: $Exports<'ref/test/object'>;
}
declare module 'ref/test/pointer.js' {
  declare module.exports: $Exports<'ref/test/pointer'>;
}
declare module 'ref/test/ref-deref.js' {
  declare module.exports: $Exports<'ref/test/ref-deref'>;
}
declare module 'ref/test/reinterpret.js' {
  declare module.exports: $Exports<'ref/test/reinterpret'>;
}
declare module 'ref/test/reinterpretUntilZeros.js' {
  declare module.exports: $Exports<'ref/test/reinterpretUntilZeros'>;
}
declare module 'ref/test/string.js' {
  declare module.exports: $Exports<'ref/test/string'>;
}
declare module 'ref/test/types.js' {
  declare module.exports: $Exports<'ref/test/types'>;
}
