// flow-typed signature: ac1da18731655ef1d5c5c0ad3d5cb9e9
// flow-typed version: <<STUB>>/resolve-url-loader_v3.0.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'resolve-url-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'resolve-url-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'resolve-url-loader/lib/engine/fail' {
  declare module.exports: any;
}

declare module 'resolve-url-loader/lib/engine/postcss' {
  declare module.exports: any;
}

declare module 'resolve-url-loader/lib/engine/rework' {
  declare module.exports: any;
}

declare module 'resolve-url-loader/lib/file-protocol' {
  declare module.exports: any;
}

declare module 'resolve-url-loader/lib/join-function' {
  declare module.exports: any;
}

declare module 'resolve-url-loader/lib/log-to-test-harness' {
  declare module.exports: any;
}

declare module 'resolve-url-loader/lib/value-processor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'resolve-url-loader/index' {
  declare module.exports: $Exports<'resolve-url-loader'>;
}
declare module 'resolve-url-loader/index.js' {
  declare module.exports: $Exports<'resolve-url-loader'>;
}
declare module 'resolve-url-loader/lib/engine/fail.js' {
  declare module.exports: $Exports<'resolve-url-loader/lib/engine/fail'>;
}
declare module 'resolve-url-loader/lib/engine/postcss.js' {
  declare module.exports: $Exports<'resolve-url-loader/lib/engine/postcss'>;
}
declare module 'resolve-url-loader/lib/engine/rework.js' {
  declare module.exports: $Exports<'resolve-url-loader/lib/engine/rework'>;
}
declare module 'resolve-url-loader/lib/file-protocol.js' {
  declare module.exports: $Exports<'resolve-url-loader/lib/file-protocol'>;
}
declare module 'resolve-url-loader/lib/join-function.js' {
  declare module.exports: $Exports<'resolve-url-loader/lib/join-function'>;
}
declare module 'resolve-url-loader/lib/log-to-test-harness.js' {
  declare module.exports: $Exports<'resolve-url-loader/lib/log-to-test-harness'>;
}
declare module 'resolve-url-loader/lib/value-processor.js' {
  declare module.exports: $Exports<'resolve-url-loader/lib/value-processor'>;
}
