// flow-typed signature: 35f05ac0de34d33c41a832e7922f9101
// flow-typed version: <<STUB>>/should_v13.1.3/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'should'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'should' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'should/as-function' {
  declare module.exports: any;
}

declare module 'should/cjs/should' {
  declare module.exports: any;
}

declare module 'should/es6/should' {
  declare module.exports: any;
}

declare module 'should/should' {
  declare module.exports: any;
}

// Filename aliases
declare module 'should/as-function.js' {
  declare module.exports: $Exports<'should/as-function'>;
}
declare module 'should/cjs/should.js' {
  declare module.exports: $Exports<'should/cjs/should'>;
}
declare module 'should/es6/should.js' {
  declare module.exports: $Exports<'should/es6/should'>;
}
declare module 'should/should.js' {
  declare module.exports: $Exports<'should/should'>;
}
