// flow-typed signature: 46691bcaf6f4db118bfb78924ede3322
// flow-typed version: <<STUB>>/testcafe-live_v^0.1.4/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'testcafe-live'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'testcafe-live' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'testcafe-live/bin/testcafe-live' {
  declare module.exports: any;
}

declare module 'testcafe-live/lib/client/index' {
  declare module.exports: any;
}

declare module 'testcafe-live/lib/controller' {
  declare module.exports: any;
}

declare module 'testcafe-live/lib/empty-test' {
  declare module.exports: any;
}

declare module 'testcafe-live/lib/file-watcher/index' {
  declare module.exports: any;
}

declare module 'testcafe-live/lib/file-watcher/modules-graph' {
  declare module.exports: any;
}

declare module 'testcafe-live/lib/index' {
  declare module.exports: any;
}

declare module 'testcafe-live/lib/log-update-async-hook/cli-cursor' {
  declare module.exports: any;
}

declare module 'testcafe-live/lib/log-update-async-hook/index' {
  declare module.exports: any;
}

declare module 'testcafe-live/lib/log-update-async-hook/restore-cursor' {
  declare module.exports: any;
}

declare module 'testcafe-live/lib/logger/base' {
  declare module.exports: any;
}

declare module 'testcafe-live/lib/logger/index' {
  declare module.exports: any;
}

declare module 'testcafe-live/lib/logger/plain' {
  declare module.exports: any;
}

declare module 'testcafe-live/lib/logger/updating' {
  declare module.exports: any;
}

declare module 'testcafe-live/lib/test-run-controller' {
  declare module.exports: any;
}

declare module 'testcafe-live/lib/test-runner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'testcafe-live/bin/testcafe-live.js' {
  declare module.exports: $Exports<'testcafe-live/bin/testcafe-live'>;
}
declare module 'testcafe-live/lib/client/index.js' {
  declare module.exports: $Exports<'testcafe-live/lib/client/index'>;
}
declare module 'testcafe-live/lib/controller.js' {
  declare module.exports: $Exports<'testcafe-live/lib/controller'>;
}
declare module 'testcafe-live/lib/empty-test.js' {
  declare module.exports: $Exports<'testcafe-live/lib/empty-test'>;
}
declare module 'testcafe-live/lib/file-watcher/index.js' {
  declare module.exports: $Exports<'testcafe-live/lib/file-watcher/index'>;
}
declare module 'testcafe-live/lib/file-watcher/modules-graph.js' {
  declare module.exports: $Exports<'testcafe-live/lib/file-watcher/modules-graph'>;
}
declare module 'testcafe-live/lib/index.js' {
  declare module.exports: $Exports<'testcafe-live/lib/index'>;
}
declare module 'testcafe-live/lib/log-update-async-hook/cli-cursor.js' {
  declare module.exports: $Exports<'testcafe-live/lib/log-update-async-hook/cli-cursor'>;
}
declare module 'testcafe-live/lib/log-update-async-hook/index.js' {
  declare module.exports: $Exports<'testcafe-live/lib/log-update-async-hook/index'>;
}
declare module 'testcafe-live/lib/log-update-async-hook/restore-cursor.js' {
  declare module.exports: $Exports<'testcafe-live/lib/log-update-async-hook/restore-cursor'>;
}
declare module 'testcafe-live/lib/logger/base.js' {
  declare module.exports: $Exports<'testcafe-live/lib/logger/base'>;
}
declare module 'testcafe-live/lib/logger/index.js' {
  declare module.exports: $Exports<'testcafe-live/lib/logger/index'>;
}
declare module 'testcafe-live/lib/logger/plain.js' {
  declare module.exports: $Exports<'testcafe-live/lib/logger/plain'>;
}
declare module 'testcafe-live/lib/logger/updating.js' {
  declare module.exports: $Exports<'testcafe-live/lib/logger/updating'>;
}
declare module 'testcafe-live/lib/test-run-controller.js' {
  declare module.exports: $Exports<'testcafe-live/lib/test-run-controller'>;
}
declare module 'testcafe-live/lib/test-runner.js' {
  declare module.exports: $Exports<'testcafe-live/lib/test-runner'>;
}
