// flow-typed signature: 199d632ea4bed2a01404611ed2be540d
// flow-typed version: <<STUB>>/testcafe-browser-provider-electron_v^0.0.6/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'testcafe-browser-provider-electron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'testcafe-browser-provider-electron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'testcafe-browser-provider-electron/lib/constants' {
  declare module.exports: any;
}

declare module 'testcafe-browser-provider-electron/lib/errors' {
  declare module.exports: any;
}

declare module 'testcafe-browser-provider-electron/lib/helpers' {
  declare module.exports: any;
}

declare module 'testcafe-browser-provider-electron/lib/hook' {
  declare module.exports: any;
}

declare module 'testcafe-browser-provider-electron/lib/index' {
  declare module.exports: any;
}

declare module 'testcafe-browser-provider-electron/lib/injectable/electron-mocks' {
  declare module.exports: any;
}

declare module 'testcafe-browser-provider-electron/lib/injectable/index' {
  declare module.exports: any;
}

declare module 'testcafe-browser-provider-electron/lib/ipc' {
  declare module.exports: any;
}

declare module 'testcafe-browser-provider-electron/lib/messages' {
  declare module.exports: any;
}

declare module 'testcafe-browser-provider-electron/lib/node-debug' {
  declare module.exports: any;
}

declare module 'testcafe-browser-provider-electron/lib/node-inspect' {
  declare module.exports: any;
}

declare module 'testcafe-browser-provider-electron/lib/utils/delay' {
  declare module.exports: any;
}

declare module 'testcafe-browser-provider-electron/lib/utils/get-config' {
  declare module.exports: any;
}

declare module 'testcafe-browser-provider-electron/lib/utils/is-absolute' {
  declare module.exports: any;
}

declare module 'testcafe-browser-provider-electron/lib/utils/is-dir' {
  declare module.exports: any;
}

declare module 'testcafe-browser-provider-electron/lib/utils/resolve-file-url' {
  declare module.exports: any;
}

declare module 'testcafe-browser-provider-electron/utils/spawn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'testcafe-browser-provider-electron/lib/constants.js' {
  declare module.exports: $Exports<'testcafe-browser-provider-electron/lib/constants'>;
}
declare module 'testcafe-browser-provider-electron/lib/errors.js' {
  declare module.exports: $Exports<'testcafe-browser-provider-electron/lib/errors'>;
}
declare module 'testcafe-browser-provider-electron/lib/helpers.js' {
  declare module.exports: $Exports<'testcafe-browser-provider-electron/lib/helpers'>;
}
declare module 'testcafe-browser-provider-electron/lib/hook.js' {
  declare module.exports: $Exports<'testcafe-browser-provider-electron/lib/hook'>;
}
declare module 'testcafe-browser-provider-electron/lib/index.js' {
  declare module.exports: $Exports<'testcafe-browser-provider-electron/lib/index'>;
}
declare module 'testcafe-browser-provider-electron/lib/injectable/electron-mocks.js' {
  declare module.exports: $Exports<'testcafe-browser-provider-electron/lib/injectable/electron-mocks'>;
}
declare module 'testcafe-browser-provider-electron/lib/injectable/index.js' {
  declare module.exports: $Exports<'testcafe-browser-provider-electron/lib/injectable/index'>;
}
declare module 'testcafe-browser-provider-electron/lib/ipc.js' {
  declare module.exports: $Exports<'testcafe-browser-provider-electron/lib/ipc'>;
}
declare module 'testcafe-browser-provider-electron/lib/messages.js' {
  declare module.exports: $Exports<'testcafe-browser-provider-electron/lib/messages'>;
}
declare module 'testcafe-browser-provider-electron/lib/node-debug.js' {
  declare module.exports: $Exports<'testcafe-browser-provider-electron/lib/node-debug'>;
}
declare module 'testcafe-browser-provider-electron/lib/node-inspect.js' {
  declare module.exports: $Exports<'testcafe-browser-provider-electron/lib/node-inspect'>;
}
declare module 'testcafe-browser-provider-electron/lib/utils/delay.js' {
  declare module.exports: $Exports<'testcafe-browser-provider-electron/lib/utils/delay'>;
}
declare module 'testcafe-browser-provider-electron/lib/utils/get-config.js' {
  declare module.exports: $Exports<'testcafe-browser-provider-electron/lib/utils/get-config'>;
}
declare module 'testcafe-browser-provider-electron/lib/utils/is-absolute.js' {
  declare module.exports: $Exports<'testcafe-browser-provider-electron/lib/utils/is-absolute'>;
}
declare module 'testcafe-browser-provider-electron/lib/utils/is-dir.js' {
  declare module.exports: $Exports<'testcafe-browser-provider-electron/lib/utils/is-dir'>;
}
declare module 'testcafe-browser-provider-electron/lib/utils/resolve-file-url.js' {
  declare module.exports: $Exports<'testcafe-browser-provider-electron/lib/utils/resolve-file-url'>;
}
declare module 'testcafe-browser-provider-electron/utils/spawn.js' {
  declare module.exports: $Exports<'testcafe-browser-provider-electron/utils/spawn'>;
}
