// flow-typed signature: 96c928b27efe4256e4683c71050f9661
// flow-typed version: <<STUB>>/weak_v1.0.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'weak'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'weak' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'weak/lib/weak' {
  declare module.exports: any;
}

declare module 'weak/test/buffer' {
  declare module.exports: any;
}

declare module 'weak/test/callback' {
  declare module.exports: any;
}

declare module 'weak/test/create' {
  declare module.exports: any;
}

declare module 'weak/test/exports' {
  declare module.exports: any;
}

declare module 'weak/test/weakref' {
  declare module.exports: any;
}

// Filename aliases
declare module 'weak/lib/weak.js' {
  declare module.exports: $Exports<'weak/lib/weak'>;
}
declare module 'weak/test/buffer.js' {
  declare module.exports: $Exports<'weak/test/buffer'>;
}
declare module 'weak/test/callback.js' {
  declare module.exports: $Exports<'weak/test/callback'>;
}
declare module 'weak/test/create.js' {
  declare module.exports: $Exports<'weak/test/create'>;
}
declare module 'weak/test/exports.js' {
  declare module.exports: $Exports<'weak/test/exports'>;
}
declare module 'weak/test/weakref.js' {
  declare module.exports: $Exports<'weak/test/weakref'>;
}
