// flow-typed signature: e6fed33a98c6f005a853436c744b8f97
// flow-typed version: <<STUB>>/@maidsafe/safe-node-app_vhttps://github.com/maidsafe/safe_app_nodejs#master/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@maidsafe/safe-node-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@maidsafe/safe-node-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@maidsafe/safe-node-app/examples/standalone/scripts/idata_asymmetric' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/examples/standalone/scripts/idata_plain' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/examples/standalone/scripts/idata_symmetric' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/examples/standalone/scripts/mdata_private' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/examples/standalone/scripts/mdata_public' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/examples/standalone/scripts/soak_test' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/api/auth' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/api/cipher_opt' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/api/crypto' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/api/emulations/index' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/api/emulations/nfs' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/api/emulations/rdf' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/api/emulations/web_id' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/api/immutable' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/api/index' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/api/mutable' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/api/web' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/app' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/consts' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/error_const' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/helpers' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/index' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/native/_app' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/native/_auth' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/native/_base' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/native/_cipher_opt' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/native/_crypto' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/native/_error' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/native/_immutable' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/native/_logging' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/native/_mutable' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/native/_nfs' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/native/_system_uri' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/native/_testing' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/native/api' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/native/helpers' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/native/lib' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/native/types' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/src/web_fetch' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/test/app' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/test/auth' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/test/browsing' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/test/cipher_opt' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/test/crypto' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/test/error_const' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/test/experimental_apis/fetch' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/test/experimental_apis/rdf' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/test/experimental_apis/web_id' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/test/experimental_apis/web' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/test/experimental_apis/xor_urls' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/test/helpers' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/test/immutable' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/test/index' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/test/mutable/entries_keys_values' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/test/mutable/index' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/test/mutable/mutation' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/test/mutable/permissions' {
  declare module.exports: any;
}

declare module '@maidsafe/safe-node-app/test/nfs' {
  declare module.exports: any;
}

// Filename aliases
declare module '@maidsafe/safe-node-app/examples/standalone/scripts/idata_asymmetric.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/examples/standalone/scripts/idata_asymmetric'>;
}
declare module '@maidsafe/safe-node-app/examples/standalone/scripts/idata_plain.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/examples/standalone/scripts/idata_plain'>;
}
declare module '@maidsafe/safe-node-app/examples/standalone/scripts/idata_symmetric.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/examples/standalone/scripts/idata_symmetric'>;
}
declare module '@maidsafe/safe-node-app/examples/standalone/scripts/mdata_private.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/examples/standalone/scripts/mdata_private'>;
}
declare module '@maidsafe/safe-node-app/examples/standalone/scripts/mdata_public.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/examples/standalone/scripts/mdata_public'>;
}
declare module '@maidsafe/safe-node-app/examples/standalone/scripts/soak_test.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/examples/standalone/scripts/soak_test'>;
}
declare module '@maidsafe/safe-node-app/src/api/auth.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/api/auth'>;
}
declare module '@maidsafe/safe-node-app/src/api/cipher_opt.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/api/cipher_opt'>;
}
declare module '@maidsafe/safe-node-app/src/api/crypto.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/api/crypto'>;
}
declare module '@maidsafe/safe-node-app/src/api/emulations/index.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/api/emulations/index'>;
}
declare module '@maidsafe/safe-node-app/src/api/emulations/nfs.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/api/emulations/nfs'>;
}
declare module '@maidsafe/safe-node-app/src/api/emulations/rdf.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/api/emulations/rdf'>;
}
declare module '@maidsafe/safe-node-app/src/api/emulations/web_id.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/api/emulations/web_id'>;
}
declare module '@maidsafe/safe-node-app/src/api/immutable.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/api/immutable'>;
}
declare module '@maidsafe/safe-node-app/src/api/index.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/api/index'>;
}
declare module '@maidsafe/safe-node-app/src/api/mutable.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/api/mutable'>;
}
declare module '@maidsafe/safe-node-app/src/api/web.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/api/web'>;
}
declare module '@maidsafe/safe-node-app/src/app.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/app'>;
}
declare module '@maidsafe/safe-node-app/src/consts.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/consts'>;
}
declare module '@maidsafe/safe-node-app/src/error_const.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/error_const'>;
}
declare module '@maidsafe/safe-node-app/src/helpers.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/helpers'>;
}
declare module '@maidsafe/safe-node-app/src/index.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/index'>;
}
declare module '@maidsafe/safe-node-app/src/native/_app.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/native/_app'>;
}
declare module '@maidsafe/safe-node-app/src/native/_auth.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/native/_auth'>;
}
declare module '@maidsafe/safe-node-app/src/native/_base.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/native/_base'>;
}
declare module '@maidsafe/safe-node-app/src/native/_cipher_opt.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/native/_cipher_opt'>;
}
declare module '@maidsafe/safe-node-app/src/native/_crypto.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/native/_crypto'>;
}
declare module '@maidsafe/safe-node-app/src/native/_error.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/native/_error'>;
}
declare module '@maidsafe/safe-node-app/src/native/_immutable.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/native/_immutable'>;
}
declare module '@maidsafe/safe-node-app/src/native/_logging.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/native/_logging'>;
}
declare module '@maidsafe/safe-node-app/src/native/_mutable.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/native/_mutable'>;
}
declare module '@maidsafe/safe-node-app/src/native/_nfs.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/native/_nfs'>;
}
declare module '@maidsafe/safe-node-app/src/native/_system_uri.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/native/_system_uri'>;
}
declare module '@maidsafe/safe-node-app/src/native/_testing.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/native/_testing'>;
}
declare module '@maidsafe/safe-node-app/src/native/api.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/native/api'>;
}
declare module '@maidsafe/safe-node-app/src/native/helpers.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/native/helpers'>;
}
declare module '@maidsafe/safe-node-app/src/native/lib.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/native/lib'>;
}
declare module '@maidsafe/safe-node-app/src/native/types.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/native/types'>;
}
declare module '@maidsafe/safe-node-app/src/web_fetch.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/src/web_fetch'>;
}
declare module '@maidsafe/safe-node-app/test/app.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/test/app'>;
}
declare module '@maidsafe/safe-node-app/test/auth.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/test/auth'>;
}
declare module '@maidsafe/safe-node-app/test/browsing.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/test/browsing'>;
}
declare module '@maidsafe/safe-node-app/test/cipher_opt.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/test/cipher_opt'>;
}
declare module '@maidsafe/safe-node-app/test/crypto.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/test/crypto'>;
}
declare module '@maidsafe/safe-node-app/test/error_const.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/test/error_const'>;
}
declare module '@maidsafe/safe-node-app/test/experimental_apis/fetch.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/test/experimental_apis/fetch'>;
}
declare module '@maidsafe/safe-node-app/test/experimental_apis/rdf.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/test/experimental_apis/rdf'>;
}
declare module '@maidsafe/safe-node-app/test/experimental_apis/web_id.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/test/experimental_apis/web_id'>;
}
declare module '@maidsafe/safe-node-app/test/experimental_apis/web.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/test/experimental_apis/web'>;
}
declare module '@maidsafe/safe-node-app/test/experimental_apis/xor_urls.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/test/experimental_apis/xor_urls'>;
}
declare module '@maidsafe/safe-node-app/test/helpers.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/test/helpers'>;
}
declare module '@maidsafe/safe-node-app/test/immutable.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/test/immutable'>;
}
declare module '@maidsafe/safe-node-app/test/index.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/test/index'>;
}
declare module '@maidsafe/safe-node-app/test/mutable/entries_keys_values.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/test/mutable/entries_keys_values'>;
}
declare module '@maidsafe/safe-node-app/test/mutable/index.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/test/mutable/index'>;
}
declare module '@maidsafe/safe-node-app/test/mutable/mutation.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/test/mutable/mutation'>;
}
declare module '@maidsafe/safe-node-app/test/mutable/permissions.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/test/mutable/permissions'>;
}
declare module '@maidsafe/safe-node-app/test/nfs.js' {
  declare module.exports: $Exports<'@maidsafe/safe-node-app/test/nfs'>;
}
