const ACTION_TYPES = {
  // Initializer
  AUTHORISE_APP: 'AUTHORISE_APP',
  GET_CONFIG: 'GET_CONFIG',
  SAVE_CONFIG: 'SAVE_CONFIG',
  SAVE_CONFIG_AND_QUIT: 'SAVE_CONFIG_AND_QUIT',

  SET_INITIALIZER_TASK: 'SET_INITIALIZER_TASK',
  STORE_NEW_ACCOUNT: 'STORE_NEW_ACCOUNT',
  NET_STATUS_CHANGED: 'NET_STATUS_CHANGED',
  RECONNECT_APP: 'RECONNECT_APP',

  // history
  UPDATE_SITE : 'UPDATE_SITE',
  DELETE_SITE : 'DELETE_SITE',
  DELETE_ALL : 'DELETE_ALL',

  //bookmarks
  UPDATE_BOOKMARK: 'UPDATE_BOOKMARK',
  DELETE_BOOKMARK: 'DELETE_BOOKMARK'
};

export default ACTION_TYPES;
